//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRSG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GRSG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Bounds
        ///Out of Bounds
        ///Your Choice.
        /// </summary>
        internal static string Bounds {
            get {
                return ResourceManager.GetString("Bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Collectables
        ///No Collectables
        ///Any Collectables
        ///Your Choice.
        /// </summary>
        internal static string Collectables {
            get {
                return ResourceManager.GetString("Collectables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Everyone
        ///Minimum Kills
        ///Any Kills
        ///Your Choice.
        /// </summary>
        internal static string Kills {
            get {
                return ResourceManager.GetString("Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Awakening
        ///A Look Inside
        ///The Climb
        ///Jacked Up
        ///Breathe In
        ///Road To Amida
        ///Run-Up
        ///The Gatekeeper
        ///Dharma City
        ///Echoes
        ///Faster
        ///In Her Own Image
        ///The Forbidden Zone
        ///Reign In Hell
        ///Things You Wouldn&apos;t Believe
        ///The Summit
        ///The Monster
        ///Your Choice.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Jump
        ///No Dash
        ///No Ledge Boost
        ///No DSJ
        ///No Super DSJ
        ///No Blink
        ///No Tempest
        ///No Surge
        ///No Overlord
        ///No Upgrades
        ///Your Choice.
        /// </summary>
        internal static string Restrictions {
            get {
                return ResourceManager.GetString("Restrictions", resourceCulture);
            }
        }
    }
}
